name: Bug report
description: Create a report to help us improve
labels: ['bug']

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: input
    id: device
    attributes:
      label: Device make/model
      placeholder: e.g. Samsung S24 Ultra
    validations:
      required: true

  - type: input
    id: android_flavor
    attributes:
      label: Android flavor
      placeholder: e.g. One UI

  - type: input
    id: android_version
    attributes:
      label: Android Version
      placeholder: e.g. 16
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Continuum version
      description: >-
        The exact version number found on the settings screen. Do not write "latest" or "current" —
        state the actual version number.
      placeholder: e.g. 8.2.5.9.1
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Additional context
      description: >-
        Any other context about the problem. If you are experiencing a crash, including the
        stacktrace will likely get it fixed sooner. Settings > Advanced > Crash Reports has a
        button that opens this form with your logs already filled in.
